version: '3.8'

services:
# Web
  php:
    links: 
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html/

# React Development Server
  react:
    container_name: react
    build:
      context: ./react
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./react:/app
      - /app/node_modules

# mySQL
  db:
    container_name: dbServer
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql-data:/var/lib/mysql

# set up for phpmyAdmin
  phpmyadmin:
    depends_on: 
      - db
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      
volumes:
  mysql-data:
  react: